services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
    - DATABASE_URL=postgres://meow:meow@postgres/postgres
    ports:
      - "8000:8000"
    restart: always
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=meow
      - POSTGRES_USER=meow
